### ISSUE TITLE
Incremental page index issue

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-infinite-scroll-changelog#1]
Hi,
I noticed a little bug when using the default's component loading behavior using the `data-path` attribute. I ended up creating a custom function, but maybe this could benefit others.

the `{n}` in the path is being replaced by the page index, however, this index starts at 0, then loads 1, 2, 3 etc... The issue is that most platforms start at page 1, not page 0 and since the content of page 1 should already be on the page, the first page to load dynamically should be page 2.

Furthermore, when using the history option, the URL will change and the user will often end up on something like `/collection/page3.html`. On these pages, when the new content to be loaded should be current page + 1 (page 4 in this example), but instead, it will load page 1. My suggestion would be to add a new data attribute called `data-current-page`, which would serve to offset the index. For example, when templating with this component, we could use something like `<main class="js-infinite-scroll" data-path="{{ '/collection/page{n}.html' }}" data-current-page="{{ collection.page }}" data-container=".js-infinite-scroll__content" data-load-btn="on" data-history="on" data-load-btn-delay="2">`. 

This could solve this issue.

**Comment by claudia-romano** [comment]
Hi Dominic,
that is a great point. Thanks for the suggestion!

We have just updated the component to include the new ```data-current-page``` attribute:
https://codyhouse.co/ds/components/info/infinite-scroll#current-page

Any additional feedback, feel free to reopen this! Cheers.
