### ISSUE TITLE
Adding a default callback function/event when content is loaded?

### ISSUE THREAD

**Issue by dominicht** [CodyHouse/cd-infinite-scroll-changelog#2]
Hi, this is just a suggestion for this component.

I know we can create custom loading functions for this component to achieve this, but it would be great if the default loading also had a callback function or event when the content is loaded. When loading content via ajax, it's very frequent we need to reapply js to newly loaded content and this would help a lot without having to create a custom loading function.

Thanks,
Dominic

**Comment by claudia-romano** [comment]
Hi Diminic, sure that makes sense. 
We have just updated the component. You can use the `content-loaded` event to detect when new content has been loaded. More info here:
https://codyhouse.co/ds/components/info/infinite-scroll#path

Cheers

**Comment by dominicht** [comment]
Thank you!
