### ISSUE TITLE
Need ability to combine Infinite Scroll component with Expandable Image Gallery Component

### ISSUE THREAD

**Issue by vibe9** [CodyHouse/cd-infinite-scroll-changelog#3]
Tried combining these two components and the newly loaded items are not added to the expandable gallery. Also, for the grid thumbnails, lazyload does not seem to work either and the placeholder image is never replaced with the data-src.

**Comment by claudia-romano** [comment]
Hi there, the Expandable Image Gallery component has been updated to be compatible with the Infinite Scroll component. You can get the updated code here:
https://codyhouse.co/ds/components/app/expandable-image-gallery

More info on how to combine the two components here:
https://codyhouse.co/ds/components/info/expandable-image-gallery#infinite-scroll

Please make sure to get the updated code of the Infinite Scroll component as well:
https://codyhouse.co/ds/components/app/infinite-scroll

Cheers!

**Comment by vibe9** [comment]
Is it possible to use this with the mixed-content lightbox gallery? https://codyhouse.co/ds/components/app/lightbox--mixed-content I am currently trying but not having any luck.

**Comment by claudia-romano** [comment]
Hi there, could you provide more info? Are you trying to use the Lightbox component with the Infinite Scroll component? 
With the Lightbox component, you have a single button opening the entire gallery. What are you loading with the Infinite Scroll? Thanks.

**Comment by vibe9** [comment]
I am using a combination of the Lightbox and Slideshow components to allow for mixed content (images and video) in a lightbox slideshow. I have a gallery of thumbnail images as the "buttons" to open each media item in the lightbox slideshow, and these thumbnail images I need to have load with infinite scroll.  I can email you a sample link to my project but I can't post it here due to it still being in dev and a URL we don't want crawled.

**Comment by claudia-romano** [comment]
Thanks for the additional info. 

When using the Infinite Scroll component, the `content-loaded` event is emitted when new content is loaded. You can use this event to detect when new lightbox galleries are added to your page. Once they have been added, you can initalise them using the `Lightbox` object.

Here you can find info on the `content-loaded` custom event:
https://codyhouse.co/ds/components/info/infinite-scroll#path

And here on how to use the `Lightbox` object:
https://codyhouse.co/ds/components/info/lightbox#dynamic-initialization

Cheers
