### ISSUE TITLE
Enhancement : infinite scroll with backend data.

### ISSUE THREAD

**Issue by elecoest** [CodyHouse/cd-infinite-scroll-changelog#4]
WIth this extension : https://infinite-scroll.com/

take few lines of code and the job is done (without any change on your example code). It's really more simple than your extension. Could you work on a similar system ? Thanks.

```
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-infinitescroll/4.0.1/infinite-scroll.pkgd.min.js" integrity="sha512-R50vU2SAXi65G4oojvP1NIAC+0WsUN2s+AbkXqoX48WN/ysG3sJLiHuB1yBGTggOu8dl/w2qsm8x4Xr8D/6Hug==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
	$('.js-adv-filter__gallery').infiniteScroll({
		path: function() {
			let pageNumber = (this.loadCount + 1) * 10;
			return `calendar.html?start=${pageNumber}`;
		},
		prefill: true,
		append: '.js-filter__item',
		history: false,
		status: '.page-load-status',
		responseBody: 'text'
	});
</script>
```

**Comment by claudia-romano** [comment]
Hi there, when using the Infinite Scroll component, you can set a data-path to specify the path of the file you need to load. You can get more info here:
https://codyhouse.co/ds/components/info/infinite-scroll#path

May I ask where the issue is with this solution? Thanks.
