### ISSUE TITLE
problem with incremental

### ISSUE THREAD

**Issue by Samanw** [CodyHouse/cd-infinite-scroll-changelog#5]
Hi, I'm facing an issue which is content won't be loaded more than one time, 
I have 3 content there but it just loads one of it which is _infinite-scroll-1.txt_
and dont load  _infinite-scroll-2.txt_  or  _infinite-scroll-3.txt_
can you help me with it, please
here is the demo
https://cp.saman-web.ir/inf/

**Comment by claudia-romano** [comment]
Hi there, please check the Info page of the component for info on how to pass the list of the files that should be loaded:
https://codyhouse.co/ds/components/info/infinite-scroll#path

Cheers!

**Comment by Samanw** [comment]
according to document and demo it should be work as it is
but it just dont.
if i set it on comma separate way its fine yet i need it to be in incremental which i have problem with
i set data-path="./infinite-scroll-{n}.html" as the files have the same name 
it should load second and third and more page but it just load the first file and nothing more

**Comment by claudia-romano** [comment]
Hi there, what error message do you receive in the console?

**Comment by Samanw** [comment]
there is no error you can check the live version here https://cp.saman-web.ir/inf/

**Comment by Samanw** [comment]
managed to fix it
it seems i had to set data-path for the first file aswell, thank you
